[package]
name = "secp"
version = "0.1.0"
entry = "start.baga"
kind = "bin"

[dependencies]
std = { path = "../../../std" }
fmrbaga = { path = "../../fmrbaga" }
ormbaga = { path = "../../ormbaga" }
jwtbaga = { path = "../../jwtbaga" }
tplbaga = { path = "../../tplbaga" }
querybaga = { path = "../../querybaga" }
pathbaga = { path = "../../pathbaga" }
imgbaga = { path = "../../imgbaga" }
officebaga = { path = "../../officebaga" }
zipbaga = { path = "../../zipbaga" }
bufbaga = { path = "../../bufbaga" }
smtpbaga = { path = "../../smtpbaga" }
wsbaga = { path = "../../wsbaga" }
chatbaga = { path = "../../chatbaga" }
davbaga = { path = "../../davbaga" }
wopibaga = { path = "../../wopibaga" }
reportbaga = { path = "../../reportbaga" }
csvbaga = { path = "../../csvbaga" }
pdfbaga = { path = "../../pdfbaga" }
xmlbaga = { path = "../../xmlbaga" }
